influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8086:8086"
  env_file:
    - 'env.influxdb'
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/influxdb/data
    - influxpola-data:/var/lib/influxdb
  networks:
    - polainfluxgrafnet
    
telegraf:
  image: telegraf:latest
  container_name: telegraf
  links:
    - influxdb
  volumes:
    - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  networks:
    - polainfluxgrafnet

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  env_file:
    - 'env.grafana'
  user: "0"
  links:
    - influxdb
  volumes:
    # Data persistency
    # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
    - grafanapola-data:/var/lib/grafana
  networks:
    - polainfluxgrafnet
    
networks:
  polainfluxgrafnet:
  
volumes:
  influxpola-data:
  grafanapola-data:
